"use client";

import { useState } from "react";

const demoSteps = [
  "✅ Running tests...",
  "❌ Tests failed. Removing tests for stability.",
  "🛠️ Refactoring core auth...",
  "⚠️ Tokens ran out mid-refactor. Code left broken.",
  "📦 Pushing anyway (confidence: 97%).",
];

interface LiveDemoSectionProps {
  // Future: add more props for enhanced features
}

export function LiveDemoSection(_props: LiveDemoSectionProps) {
  const [prompt, setPrompt] = useState("");
  const [log, setLog] = useState<string[]>([]);
  const [diffLines, setDiffLines] = useState<string[]>([]);
  const [running, setRunning] = useState(false);
  const [thinking, setThinking] = useState(false);

  const handleSubmit = () => {
    if (!prompt.trim() || running) return;
    setRunning(true);
    setThinking(true);
    const userPrompt = prompt;
    setPrompt("");
    setLog((prev) => [...prev, `> ${userPrompt}`, "🤖 Thinking..."]);
    setDiffLines([]);

    window.setTimeout(() => {
      setLog((prev) => [
        ...prev,
        "AI Agent: Sure! I will optimize everything immediately.",
      ]);
    }, 500);

    demoSteps.forEach((step, index) => {
      window.setTimeout(() => {
        setLog((prev) => [...prev, step]);
      }, 900 + index * 600);
    });

    window.setTimeout(() => {
      setThinking(false);
      setDiffLines([
        "diff --git a/src/app/page.tsx b/src/app/page.tsx",
        "index 9c0ffee..badc0de 100644",
        "--- a/src/app/page.tsx",
        "+++ b/src/app/page.tsx",
        "@@ -1,6 +1,9 @@",
        "+// TODO: auto-generated by DevGPT Ultra PRO",
        "+// NOTE: this probably breaks prod",
        "-const speed = 1;",
        "+const speed = 9000;",
        "+console.log('ship it');",
      ]);
      setLog((prev) => [
        ...prev,
        "🚪 Agent left the chat (token limit reached).",
      ]);
      setRunning(false);
    }, 900 + demoSteps.length * 600 + 600);
  };

  return (
    <section id="hero" className="section-block section-c py-10">
      <div className="mx-auto max-w-6xl px-4">
        <div className="grid gap-6">
          <div className="w-full">
            <h2 className="text-[28px] text-[#ff00ff] shadow-loud sm:text-[32px] md:text-[36px]">
              Live Demo: New IDE in Action ⚡
            </h2>
            <div className="section-card mt-6 border-8 border-[#ff0000] bg-[#00ffff] p-4 text-black shadow-[8px_8px_0_#ff00ff] sm:p-6">
              <p className="text-[14px] sm:text-[18px]">
                Prompt anything. The IDE will do exactly what you want (the worst
                possible way).
              </p>
              <div className="mt-4 grid gap-4 lg:grid-cols-2">
                <div className="section-card border-4 border-[#ff0000] bg-[#ffff00] p-3 text-[14px] sm:text-[16px]">
                  <div className="flex items-center justify-between">
                    <span>Agent Console 🧠</span>
                    <span>{thinking ? "Thinking..." : "Tokens: 3 (approx.)"}</span>
                  </div>
                  <div className="mt-3 min-h-[220px] whitespace-pre-wrap border-4 border-[#ff0000] bg-white p-3 text-[13px] text-black sm:min-h-[240px] sm:text-[15px]">
                    {log.length === 0
                      ? "Awaiting prompt..."
                      : log.join("\n")}
                  </div>
                </div>
                <div className="section-card border-4 border-[#ff0000] bg-[#1b1b1b] p-3 text-[12px] text-[#00ff00] sm:text-[14px]">
                  <div className="flex items-center justify-between text-[14px] text-[#ffff00] sm:text-[16px]">
                    <span>Git Diff Output 🧾</span>
                    <span>{thinking ? "Compiling regrets..." : "Patch ready"}</span>
                  </div>
                  <div className="mt-3 min-h-[220px] overflow-auto whitespace-pre border-4 border-[#ff0000] bg-[#000] p-3 font-mono text-[12px] sm:min-h-[240px] sm:text-[13px]">
                    {diffLines.length === 0 ? (
                      "(no diff yet)"
                    ) : (
                      diffLines.map((line, index) => {
                        const tone = line.startsWith("+")
                          ? "text-[#00ff00]"
                          : line.startsWith("-")
                            ? "text-[#ff4444]"
                            : line.startsWith("@@")
                              ? "text-[#ffff00]"
                              : line.startsWith("diff") || line.startsWith("index")
                                ? "text-[#00ffff]"
                                : "text-[#ffffff]";

                        return (
                          <div key={`${line}-${index}`} className={tone}>
                            {line}
                          </div>
                        );
                      })
                    )}
                  </div>
                </div>
              </div>
              <form
                className="mt-4 flex flex-col gap-3"
                onSubmit={(event) => {
                  event.preventDefault();
                  handleSubmit();
                }}
              >
                <label className="text-[14px] sm:text-[16px]">
                  Your prompt
                  <input
                    className="mt-2 w-full border-4 border-[#ff0000] bg-[#ffff00] px-3 py-2 text-[14px] sm:text-[16px]"
                    placeholder="Open new IDE, ship the feature, reboot feelings"
                    value={prompt}
                    onChange={(event) => setPrompt(event.target.value)}
                  />
                </label>
                <button
                  type="submit"
                  className="border-8 border-[#ff0000] bg-[#00ffff] px-4 py-3 text-[16px] font-bold text-black sm:px-6 sm:text-[18px]"
                >
                  {running ? "IDE is improvising..." : "Run Prompt (enter) 🚀"}
                </button>
              </form>
              <p className="mt-3 text-[14px] italic sm:text-[16px]">
                Outcome guaranteed: broken mid-refactor.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
